version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=
      - POSTGRESQL_DATABASE=apisolid
      - ALLOW_EMPTY_PASSWORD=yes